course = "   Python programming   "
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.find("pro"))
print(course.replace("o", "j"))
print("pro" in course)
print("swift" not in course)
print(course)
